name: FAST-VQA-M-MGTV
num_epochs: 40
l_num_epochs: 10
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 16
num_workers: 6

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
        args:
            phase: train
            random_crop: false
            #anno_file: ./examplar_data_labels/train_labels.txt
            #data_prefix: ../datasets/LSVQ
            anno_file: ./examplar_data_labels/mgtv_training.txt
            data_prefix: ../mgtv_vqa/MGTV_VQA_DATA/1.MGTV_OGC_V1_dataset/training
            sample_types:
                fragments:
                    fragments_h: 4
                    fragments_w: 4
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 8
            clip_len: 16
            frame_interval: 2
            num_clips: 1
    val:
        type: FusionDataset
        args:
            phase: test
            #anno_file: ./examplar_data_labels/LIVE_VQC/labels.txt
            #data_prefix: ../datasets/LIVE_VQC
            anno_file: ./examplar_data_labels/mgtv_validation.txt
            data_prefix: ../mgtv_vqa/MGTV_VQA_DATA/1.MGTV_OGC_V1_dataset/validation
            sample_types:
                #resize:
                #    size_h: 224
                #    size_w: 224
                fragments:
                    fragments_h: 4
                    fragments_w: 4
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 8
            clip_len: 16
            frame_interval: 2
            num_clips: 4
        
model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                checkpoint: false
                pretrained: 
        backbone_size: swin_tiny_grpb_m
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ./pretrained_weights/fast-m_vqa_v0_3.pth
test_load_path: ./pretrained_weights/FAST-VQA-B-Refactor-From-Scratch_s_dev_v0.0.pth


    
        

