name: MoLEx-MsExperts-F
num_epochs: 0
l_num_epochs: 3
warmup_epochs: 1
ema: true
save_model: true
batch_size: 16
num_workers: 6

wandb:
    project_name: MoLEx_for_CVPR_2023

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/train_labels.txt
            data_prefix: ../datasets/LSVQ
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1

            
    val-livevqc:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/LIVE_VQC/labels.txt
            data_prefix: ../datasets/LIVE_VQC/
            sample_types:
                #resize:
                #    size_h: 224
                #    size_w: 224
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4





model:
    type: DiViDeAddEvaluator
    args:
        multi: true
        backbone:
            fragments:
                type: swin_tiny_grpb
                checkpoint: false
                pretrained:
        backbone_preserve_keys: fragments
        divide_head: true
        vqa_head:
            in_channels: 1440
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ./pretrained_weights/FAST_VQA_B_1*4.pth

    
        
