name: MoLEx-MsExperts-T
num_epochs: 0
l_num_epochs: 3
warmup_epochs: 1
ema: true
save_model: true
batch_size: 16
num_workers: 6

wandb:
    project_name: MoLEx_for_CVPR_2023

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/train_labels.txt
            data_prefix: ../datasets/LSVQ
            sample_types:
                resize:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1
            
    val-livevqc:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/LIVE_VQC/labels.txt
            data_prefix: ../datasets/LIVE_VQC/
            sample_types:
                resize:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4






model:
    type: DiViDeAddEvaluator
    args:
        multi: true
        backbone:
            resize:
                type: conv_tiny
        backbone_preserve_keys: resize
        divide_head: true
        vqa_head:
            in_channels: 672
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ./pretrained_weights/FAST-VQA-with-Conv-Backbone-Resize_s_dev_v0.0.pth

    
        
