name: Finetune_for_KoNViD

num_epochs: 10
l_num_epochs: 10
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 16
num_workers: 6

need_upsampled: true
need_feat: true
need_fused: true

split_seed: 42

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
            phase: train
            random_crop: false
            anno_file: ./examplar_data_labels/KoNViD/labels.txt
            data_prefix: ../datasets/KoNViD
            sample_types:
                fragments_up:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                resize_up:
                    size_h: 224
                    size_w: 224
                fragments:
                    fragments_h: 4
                    fragments_w: 4
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                resize:
                    size_h: 128
                    size_w: 128
            clip_len: 32
            frame_interval: 2
            num_clips: 1
    val:
        type: FusionDataset
        args:
            phase: test
            random_crop: false
            anno_file: ./examplar_data_labels/KoNViD/labels.txt
            data_prefix: ../datasets/KoNViD
            sample_types:
                fragments:
                    fragments_h: 4
                    fragments_w: 4
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                resize:
                    size_h: 128
                    size_w: 128
            clip_len: 32
            frame_interval: 2
            num_clips: 4

model:
    type: DiViDeAddEvaluator
    args:
        divide_head: true # if true, different branches will not share head
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ./pretrained_weights/DiViDe-MRSSSL-DivideHead-BiLearn_s_dev_v0.0.pth
test_load_path: ./pretrained_weights/DiViDe-MRSSSL-DivideHead-BiLearn_s_dev_v0.0.pth



    
        
